import { useState, useEffect } from "react";
import { CheckCircle2, ShieldAlert } from "lucide-react";
import { api } from "../services/api";
import type { AlertItem, AlertStatus } from "../types/dashboard";
import { LoadingState } from "./LoadingState";
import { ErrorState } from "./ErrorState";
import { EmptyState } from "./EmptyState";

export function AlertsSection() {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("ALL");

  const loadAlerts = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.getAlerts();
      setAlerts(res.alerts);
    } catch {
      setError("Unable to load alerts.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const handleUpdateStatus = async (id: string, newStatus: AlertStatus) => {
    try {
      const updated = await api.updateAlertStatus(id, newStatus);
      setAlerts((prev) => prev.map((a) => (a.id === id ? updated : a)));
    } catch {
      // retain state on failure
    }
  };

  if (loading) return <LoadingState lines={4} label="Scanning for active alerts…" />;
  if (error) return <ErrorState message={error} onRetry={loadAlerts} />;

  const filteredAlerts = alerts.filter((a) => {
    if (statusFilter === "ALL") return true;
    return a.status === statusFilter;
  });

  return (
    <div className="dashboard-stack">
      <div className="panel">
        <div className="panel-header">
          <h2>Intelligent Alert Center</h2>
          <span className="panel-sub">
            Real-time conditions-based alerts generated by pipeline metrics
          </span>
          <div className="filter-group">
            {["ALL", "ACTIVE", "ACKNOWLEDGED", "RESOLVED"].map((f) => (
              <button
                key={f}
                type="button"
                className={`btn btn-sm ${statusFilter === f ? "btn-primary" : ""}`}
                onClick={() => setStatusFilter(f)}
              >
                {f}
              </button>
            ))}
          </div>
        </div>

        {filteredAlerts.length === 0 ? (
          <EmptyState message={`No ${statusFilter.toLowerCase()} alerts found.`} />
        ) : (
          <div className="alerts-list">
            {filteredAlerts.map((alert) => (
              <div key={alert.id} className={`alert-card alert-sev-${alert.severity.toLowerCase()}`}>
                <div className="alert-header">
                  <div className="alert-title-row">
                    <ShieldAlert size={18} />
                    <h3>{alert.title}</h3>
                  </div>
                  <span className={`badge badge-${alert.severity.toLowerCase()}`}>
                    {alert.severity}
                  </span>
                </div>
                <p className="alert-desc">{alert.description}</p>
                <div className="alert-footer">
                  <span className="alert-meta">
                    Source: <strong>{alert.source}</strong> •{" "}
                    {new Date(alert.timestamp).toLocaleTimeString()}
                  </span>
                  <div className="alert-actions">
                    {alert.status === "ACTIVE" && (
                      <button
                        type="button"
                        className="btn btn-sm"
                        onClick={() => handleUpdateStatus(alert.id, "ACKNOWLEDGED")}
                      >
                        Acknowledge
                      </button>
                    )}
                    {alert.status !== "RESOLVED" && (
                      <button
                        type="button"
                        className="btn btn-sm btn-success"
                        onClick={() => handleUpdateStatus(alert.id, "RESOLVED")}
                      >
                        <CheckCircle2 size={12} /> Resolve
                      </button>
                    )}
                    {alert.status === "RESOLVED" && (
                      <span className="text-sub">✓ Resolved</span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
